//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                accountId: {
                    name: "accountId",
                    type: "String"
                },
                providerId: {
                    name: "providerId",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                accessToken: {
                    name: "accessToken",
                    type: "String",
                    optional: true
                },
                refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    optional: true
                },
                idToken: {
                    name: "idToken",
                    type: "String",
                    optional: true
                },
                accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String",
                    optional: true
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("account") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }, { name: "@email" }]
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                banned: {
                    name: "banned",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                banReason: {
                    name: "banReason",
                    type: "String",
                    optional: true
                },
                banExpires: {
                    name: "banExpires",
                    type: "DateTime",
                    optional: true
                },
                phone: {
                    name: "phone",
                    type: "String",
                    optional: true
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                chats: {
                    name: "chats",
                    type: "Chat",
                    array: true,
                    relation: { opposite: "user" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "user" }
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "user" }
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("user") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Chat: {
            name: "Chat",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "chats", fields: ["organizationId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]) }] }],
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]),
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "chats", fields: ["userId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]) }] }],
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]),
                    foreignKeyFor: [
                        "user"
                    ]
                },
                title: {
                    name: "title",
                    type: "String",
                    optional: true
                },
                model: {
                    name: "model",
                    type: "String",
                    optional: true
                },
                messages: {
                    name: "messages",
                    type: "ChatMessage",
                    array: true,
                    relation: { opposite: "chat" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]), "==", ExpressionUtils.field("organizationId")), "&&", ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]), "==", ExpressionUtils.field("userId"))) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("chat") }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("organizationId")]) }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ChatMessage: {
            name: "ChatMessage",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                chat: {
                    name: "chat",
                    type: "Chat",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("chatId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "messages", fields: ["chatId"], references: ["id"], onDelete: "Cascade" }
                },
                chatId: {
                    name: "chatId",
                    type: "String",
                    foreignKeyFor: [
                        "chat"
                    ]
                },
                role: {
                    name: "role",
                    type: "String"
                },
                parts: {
                    name: "parts",
                    type: "String"
                },
                model: {
                    name: "model",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("chat"), ["organization", "id"]), "==", ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"])), "&&", ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]), "==", ExpressionUtils.member(ExpressionUtils.field("chat"), ["userId"]))) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("chatMessage") }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("chatId")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Organization: {
            name: "Organization",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                slug: {
                    name: "slug",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                logo: {
                    name: "logo",
                    type: "String",
                    optional: true
                },
                defaultLocale: {
                    name: "defaultLocale",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("pt-BR") }] }],
                    default: "pt-BR"
                },
                defaultCurrencyCode: {
                    name: "defaultCurrencyCode",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("BRL") }] }],
                    default: "BRL"
                },
                metadata: {
                    name: "metadata",
                    type: "String",
                    optional: true
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "organization" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "organization" }
                },
                businessUnits: {
                    name: "businessUnits",
                    type: "BusinessUnit",
                    array: true,
                    relation: { opposite: "organization" }
                },
                chats: {
                    name: "chats",
                    type: "Chat",
                    array: true,
                    relation: { opposite: "organization" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("organization") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                slug: { type: "String" }
            }
        },
        Member: {
            name: "Member",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                role: {
                    name: "role",
                    type: "String"
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "members", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "members", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("member") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Invitation: {
            name: "Invitation",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                email: {
                    name: "email",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                inviterId: {
                    name: "inviterId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "invitations", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("inviterId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "invitations", fields: ["inviterId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("invitation") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        BusinessUnit: {
            name: "BusinessUnit",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "businessUnits", fields: ["organizationId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]) }] }],
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]),
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                isActive: {
                    name: "isActive",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                name: {
                    name: "name",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }] }]
                },
                legalName: {
                    name: "legalName",
                    type: "String",
                    optional: true
                },
                taxId: {
                    name: "taxId",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]), "==", ExpressionUtils.field("organizationId")) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("businessUnit") }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("organizationId")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Session: {
            name: "Session",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                token: {
                    name: "token",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    optional: true
                },
                userAgent: {
                    name: "userAgent",
                    type: "String",
                    optional: true
                },
                impersonatedBy: {
                    name: "impersonatedBy",
                    type: "String",
                    optional: true
                },
                activeOrganizationId: {
                    name: "activeOrganizationId",
                    type: "String",
                    optional: true
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("session") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                token: { type: "String" }
            }
        },
        Verification: {
            name: "Verification",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                identifier: {
                    name: "identifier",
                    type: "String"
                },
                value: {
                    name: "value",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("verification") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Auth: {
            name: "Auth",
            fields: {
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@id" }]
                },
                organizationId: {
                    name: "organizationId",
                    type: "String"
                }
            },
            attributes: [
                { name: "@@auth" }
            ]
        },
        BaseModel: {
            name: "BaseModel",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                }
            }
        }
    } as const;
    authType = "Auth" as const;
    plugins = {};
}
export const schema = new SchemaType();
